### ISSUE TITLE
Make entire application look pretty

### ISSUE THREAD

**Issue by msoucy** [chopshop-166/ChopshopSignin#35]
@jeffaburke

**Comment by jeffaburke** [comment]
- [x] Make Profile Look Better (On mobile mainly)
- [ ] Add Buttons to the home page the directly lead to sign in/register (this would put those out of the nav bar and would allow for the home page to have some content)

**Comment by msoucy** [comment]
If you could get the admin/active page buttons to be on one line instead of two, that would be beautiful.

**Comment by jeffaburke** [comment]
I tried today but i'll keep trying tomorrow

**Comment by msoucy** [comment]
Thought: the index page should probably have the current user's QR code if they're signed in, for quick access.
Also the profile page's list of badges should probably have the link color changed (or make them buttons?)

**Comment by msoucy** [comment]
Please take a look at the password change and user forbidden pages and get them up to par with the login/register pages

**Comment by msoucy** [comment]
I'm merging the Pretty branch into Web, for the sake of getting everything in one place. I'll open separate issues for the remaining things.
