### ISSUE TITLE
Bar code generation

### ISSUE THREAD

**Issue by msoucy** [chopshop-166/ChopshopSignin#4]
Program should provide a barcode generation system, to avoid teams having to find/purchase their own.

**Comment by msoucy** [comment]
Suggest using GenCode128 which is accessible via NuGet. The barcodes in the current system use CODE_128, but I believe that that's a function of the scanner itself instead of the program.

**Comment by msoucy** [comment]
This can be solved by using the [code128 Python module](https://bitbucket.org/01100101/code128/overview) like so:

``` sh
code128 'Lastname, Firstname' filename.svg
```

This can easily be done in bulk, but requires people to start using an entirely separate ecosystem (Python)

**Comment by mwoden** [comment]
Going to just recommend using Zint rather than incorporating this into the tool itself

**Comment by msoucy** [comment]
:+1:
